# Generated by Django 2.0.3 on 2018-04-16 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=50)),
                ('c_locality', models.CharField(max_length=25)),
                ('c_state', models.CharField(max_length=25)),
                ('c_country', models.CharField(max_length=25)),
                ('c_pincode', models.IntegerField()),
                ('c_link', models.CharField(max_length=100)),
                ('c_img', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=25)),
                ('g_op_rank', models.IntegerField()),
                ('g_cl_rank', models.IntegerField()),
                ('obc_op_rank', models.IntegerField()),
                ('obc_cl_rank', models.IntegerField()),
                ('sc_op_rank', models.IntegerField()),
                ('sc_cl_rank', models.IntegerField()),
                ('st_op_rank', models.IntegerField()),
                ('st_cl_rank', models.IntegerField()),
                ('hm_g_op_rank', models.IntegerField()),
                ('hm_g_cl_rank', models.IntegerField()),
                ('hm_obc_op_rank', models.IntegerField()),
                ('hm_obc_cl_rank', models.IntegerField()),
                ('hm_sc_op_rank', models.IntegerField()),
                ('hm_sc_cl_rank', models.IntegerField()),
                ('hm_st_op_rank', models.IntegerField()),
                ('hm_st_cl_rank', models.IntegerField()),
                ('college', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.College')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(default=0)),
                ('home_state', models.CharField(max_length=50)),
                ('mains_rank', models.IntegerField()),
                ('advanced_rank', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('mail', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.User'),
        ),
    ]
