# Generated by Django 2.0.3 on 2018-04-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180417_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='c_img',
        ),
        migrations.AlterField(
            model_name='user',
            name='mail',
            field=models.EmailField(max_length=100),
        ),
    ]
