# Generated by Django 2.0.3 on 2018-04-17 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180417_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='g_cl_rank',
            new_name='cl_rank',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='g_op_rank',
            new_name='op_rank',
        ),
        migrations.RemoveField(
            model_name='department',
            name='hm_g_cl_rank',
        ),
        migrations.RemoveField(
            model_name='department',
            name='hm_g_op_rank',
        ),
        migrations.RemoveField(
            model_name='department',
            name='hm_obc_cl_rank',
        ),
        migrations.RemoveField(
            model_name='department',
            name='hm_obc_op_rank',
        ),
        migrations.RemoveField(
            model_name='department',
            name='hm_sc_cl_rank',
        ),
        migrations.RemoveField(
            model_name='department',
            name='hm_sc_op_rank',
        ),
        migrations.RemoveField(
            model_name='department',
            name='hm_st_cl_rank',
        ),
        migrations.RemoveField(
            model_name='department',
            name='hm_st_op_rank',
        ),
        migrations.RemoveField(
            model_name='department',
            name='obc_cl_rank',
        ),
        migrations.RemoveField(
            model_name='department',
            name='obc_op_rank',
        ),
        migrations.RemoveField(
            model_name='department',
            name='sc_cl_rank',
        ),
        migrations.RemoveField(
            model_name='department',
            name='sc_op_rank',
        ),
        migrations.RemoveField(
            model_name='department',
            name='st_cl_rank',
        ),
        migrations.RemoveField(
            model_name='department',
            name='st_op_rank',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='category',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='home_state',
        ),
    ]
