# Generated by Django 2.0.3 on 2018-04-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20180417_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='c_value',
            field=models.IntegerField(default=0),
        ),
    ]
