# Generated by Django 2.0.3 on 2018-04-17 12:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_college_c_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='cl_rank',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(250000)]),
        ),
        migrations.AlterField(
            model_name='department',
            name='op_rank',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
